# Generated by Django 2.0.7 on 2018-07-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='num_posts',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
